[workspace]
authors = ["Ryan Volz <rvolz@mit.edu>"]
channels = ["https://prefix.dev/conda-forge"]
name = "maia_waterfall_widget"
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "osx-64", "win-64"]
preview = ["pixi-build"]

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.build.config]
ignore-pypi-mapping = false

[package.build-dependencies]
nodejs = "*"
rust = "*"
wasm-pack = "*"
rust-std-wasm32-unknown-unknown = "*"

[dev]
maia_waterfall_widget = { path = "." }

[pypi-dependencies]
maia_waterfall_widget = { path = ".", editable = true }

[feature.example.dependencies]
watchfiles = "==1.2.0"
jupyterlab = "==4.5.7"
pillow = "==12.2.0"
paho-mqtt = "==2.1.0"

[feature.pkg.dependencies]
maia_waterfall_widget = { path = "." }

[environments]
default = { features = ["dev", "example"], solve-group = "default"}
test = { features = ["example", "pkg"], solve-group = "default", no-default-feature = true }

[feature.dev.tasks]
build = "uv build"
build-bindings = "npm run wasm"
cargo-update = "cargo update --manifest-path bindings/Cargo.toml"
reinstall = "pixi reinstall -e default maia_waterfall_widget"
vite = "npx vite --host localhost --port 5173 --strictPort"

[feature.example.tasks]
example = { cmd = "jupyter lab example.ipynb", default-environment = "default"}
